// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AmisRender: typeof import('./src/components/libraries/AmisRender.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    BasicLayout: typeof import('./src/components/BasicLayout.vue')['default']
    Container: typeof import('./src/components/CustomPage/container/index.vue')['default']
    CustomPage: typeof import('./src/components/CustomPage/index.vue')['default']
    Display: typeof import('./src/components/CustomPage/container/display.vue')['default']
    FileSelect: typeof import('./src/components/Base/FileSelect.vue')['default']
    FileUpload: typeof import('./src/components/Base/FileUpload.vue')['default']
    Media: typeof import('./src/components/CustomPage/media/index.vue')['default']
    Navigation: typeof import('./src/components/PageBuilder/navigation.vue')['default']
    Operate: typeof import('./src/components/CustomPage/container/operate.vue')['default']
    OrderShip: typeof import('./src/components/modals/orderShip.vue')['default']
    PageBuilder: typeof import('./src/components/PageBuilder/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Static: typeof import('./src/components/CustomPage/container/static.vue')['default']
    Text: typeof import('./src/components/CustomPage/text/index.vue')['default']
  }
}
